spring.application.name=irctc

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/irctc_bookings
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Enable health details
management.endpoint.health.show-details=always

# Base path for actuator endpoints
management.endpoints.web.base-path=/actuator

# Enable health endpoint
management.endpoint.health.enabled=true

# Enable info endpoint
management.endpoint.info.enabled=true

# Enable metrics endpoint
management.endpoint.metrics.enabled=true

# Enable beans endpoint
management.endpoint.beans.enabled=true

# Enable mappings endpoint
management.endpoint.mappings.enabled=true

# Enable env endpoint
management.endpoint.env.enabled=true

# Enable loggers endpoint
management.endpoint.loggers.enabled=true

# Enable threaddump endpoint
management.endpoint.threaddump.enabled=true

# Enable heapdump endpoint
management.endpoint.heapdump.enabled=true

info.app.name=Train India Booking System
info.app.version=1.0.0
info.app.description=Train Booking REST API
info.app.developer=Arvind